// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jcivwvckvtybgzmiqowc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImpjaXZ3dmNrdnR5Ymd6bWlxb3djIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDU1MjE2NTIsImV4cCI6MjA2MTA5NzY1Mn0.iCHH5_wD6VSKJzZ2Ana6fbw-JB_6fvYj6ZohW9c6LLM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);